//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleScore
    {
        public int Scoreid { get; set; }
        public int icerikid { get; set; }
        public int Score { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
